

-- Bảng ROLE lưu trữ các vai trò của người dùng
CREATE TABLE ROLE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(20) NOT NULL
);
GO

-- Bảng ACCOUNT lưu trữ thông tin tài khoản đăng nhập của người dùng
CREATE TABLE ACCOUNT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USERNAME VARCHAR(30) UNIQUE NOT NULL,
    PASSWORD VARCHAR(30) NOT NULL,
    ROLE_ID INT NOT NULL,
    CONSTRAINT FK_Account_Role FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
);
GO

-- Bảng INFORMATION_PERSON lưu trữ thông tin cá nhân của người dùng
CREATE TABLE INFORMATION_PERSON (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    FULLNAME NVARCHAR(50) NOT NULL,
    CitizenID CHAR(12) UNIQUE NOT NULL,
    BIRTHDATE DATE,
    ADDRESS TEXT,
    AccountID INT NOT NULL,
    CONSTRAINT FK_InformationPerson_Account FOREIGN KEY (AccountID) REFERENCES ACCOUNT(ID)
);
GO

CREATE TABLE PERMISSION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(255)
);

CREATE TABLE USER_PERMISSION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    USER_ID INT NOT NULL,
    PERMISSION_ID INT NOT NULL,
    CONSTRAINT FK_UserPermission_User FOREIGN KEY (USER_ID) REFERENCES ACCOUNT(ID),
    CONSTRAINT FK_UserPermission_Permission FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSION(ID)
);

-- Bảng ROOM_TYPE để lưu trữ loại phòng
CREATE TABLE ROOM_TYPE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(30) NOT NULL
);
GO

-- Bảng ROOM để lưu trữ thông tin phòng
CREATE TABLE ROOM (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ROOM_NUMBER NVARCHAR(10) NOT NULL,
    ROOM_TYPE_ID INT NOT NULL,
    CONSTRAINT FK_Room_RoomType FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPE(ID)
);
GO

-- Bảng SERVICE để lưu trữ thông tin dịch vụ
CREATE TABLE SERVICE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(50) NOT NULL,
    DESCRIPTION NVARCHAR(255)
);
GO

-- Bảng ROOM_SERVICE để lưu trữ thông tin dịch vụ của từng phòng
CREATE TABLE ROOM_SERVICE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ROOM_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    CONSTRAINT FK_RoomService_Room FOREIGN KEY (ROOM_ID) REFERENCES ROOM(ID),
    CONSTRAINT FK_RoomService_Service FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(ID)
);
GO

CREATE TABLE BOOKING (
    ID INT IDENTITY(1,1) PRIMARY KEY, -- Khóa chính tự động tăng
    IF_ID INT NOT NULL, -- Khóa ngoại tham chiếu đến bảng khách hàng
    RoomID INT NOT NULL, -- Khóa ngoại tham chiếu đến bảng phòng
    BookingDate DATE NOT NULL DEFAULT GETDATE(), -- Ngày đặt phòng
    CheckInDate DATE NOT NULL, -- Ngày nhận phòng
    CheckOutDate DATE NOT NULL, -- Ngày trả phòng
    Status NVARCHAR(20) NOT NULL, -- Trạng thái đặt phòng (ví dụ: Confirmed, Cancelled)
    CONSTRAINT FK_Booking_Information FOREIGN KEY (IF_ID) REFERENCES INFORMATION_PERSON(ID), -- Ràng buộc khóa ngoại
    CONSTRAINT FK_Booking_Room FOREIGN KEY (RoomID) REFERENCES ROOM(ID) -- Ràng buộc khóa ngoại
);
GO

CREATE TABLE BOOKING_SERVICE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    BOOKING_ID INT NOT NULL,
    SERVICE_ID INT NOT NULL,
    CONSTRAINT FK_BookingService_Booking FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(ID),
    CONSTRAINT FK_BookingService_Service FOREIGN KEY (SERVICE_ID) REFERENCES SERVICE(ID)
);
GO

CREATE TABLE PAYMENT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    BOOKING_ID INT NOT NULL,
    AMOUNT DECIMAL(10, 2) NOT NULL,
    PAYMENTDATE DATE NOT NULL DEFAULT GETDATE(),
    PaymentMethod NVARCHAR(20),
    CONSTRAINT FK_Payment_Booking FOREIGN KEY (BOOKING_ID) REFERENCES BOOKING(ID)
);
GO
